## import libraries


#### stop words
#### tokenization
#### lower +stemming
#### exclude punc
#### bow

In [2]:
import nltk 
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

## read data

In [3]:
datatsv=pd.read_csv("Restaurant_Reviews.tsv",delimiter='\t')

In [4]:
datatsv.head(20)

Review  Liked
0                            Wow... Loved this place.      1
1                                  Crust is not good.      0
2           Not tasty and the texture was just nasty.      0
3   Stopped by during the late May bank holiday of...      1
4   The selection on the menu was great and so wer...      1
5      Now I am getting angry and I want my damn pho.      0
6               Honeslty it didn't taste THAT fresh.)      0
7   The potatoes were like rubber and you could te...      0
8                           The fries were great too.      1
9                                      A great touch.      1
10                           Service was very prompt.      1
11                                 Would not go back.      0
12  The cashier had no care what so ever on what I...      0
13  I tried the Cape Cod ravoli, chicken, with cra...      1
14  I was disgusted because I was pretty sure that...      0
15  I was shocked because no signs indicate cash o...      0
16                                Highly recommended.      1
17             Waitress was a little slow in service.      0
18  This place is not worth your time, let alone V...      0
19                               did not like at all.      0

In [5]:
datatsv.__len__()

1000

## preprocessing

In [6]:
import re
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to C:\Users\noor
[nltk_data]     waleed\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

#### importing important modules

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
lem=PorterStemmer()



In [8]:
stop_words=stopwords.words("english")

In [9]:
rev=datatsv['Review'][0]

In [10]:
rev

'Wow... Loved this place.'

In [11]:
tokens=rev.split()
tokens

['Wow...', 'Loved', 'this', 'place.']

In [12]:
clean_text=[]
for word in tokens:
    if word.lower() not in stop_words:
        clean_text.append(word.lower())

In [13]:
print(tokens)
print(clean_text)

['Wow...', 'Loved', 'this', 'place.']
['wow...', 'loved', 'place.']


In [14]:
lem_words=[]
for word in clean_text:
    lem_words.append(lem.stem(word))

In [15]:
lem_words

['wow...', 'love', 'place.']

In [67]:
corpusdata = []
for i in range (0, 1000):
    review=re.sub('^\s+',"",datatsv['Review'][i]) # remove space 
    review=re.sub('\s+$',"",datatsv['Review'][i]) 
    review=re.sub('\s\d+\s',"",datatsv['Review'][i]) 
    review=re.sub('\s[a-zA-Z]\s',"",datatsv['Review'][i]) 
    review=re.sub('[^\w\s]',"",datatsv['Review'][i])  ## remove punc

   
    
    review = review.lower()
    review = review.split()
    review = [lem.stem(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    corpusdata.append(review)
    
    ## without the join the corpus data is list of list
    

In [57]:
print(len(review))

12


In [58]:
print(len(corpusdata))

1000


In [59]:
print(corpusdata)

[['wow', 'love', 'place'], ['crust', 'good'], ['tasti', 'textur', 'nasti'], ['stop', 'late', 'may', 'bank', 'holiday', 'rick', 'steve', 'recommend', 'love'], ['select', 'menu', 'great', 'price'], ['get', 'angri', 'want', 'damn', 'pho'], ['honeslti', 'didnt', 'tast', 'fresh'], ['potato', 'like', 'rubber', 'could', 'tell', 'made', 'ahead', 'time', 'kept', 'warmer'], ['fri', 'great'], ['great', 'touch'], ['servic', 'prompt'], ['would', 'go', 'back'], ['cashier', 'care', 'ever', 'say', 'still', 'end', 'wayyy', 'overpr'], ['tri', 'cape', 'cod', 'ravoli', 'chicken', 'cranberrymmmm'], ['disgust', 'pretti', 'sure', 'human', 'hair'], ['shock', 'sign', 'indic', 'cash'], ['highli', 'recommend'], ['waitress', 'littl', 'slow', 'servic'], ['place', 'worth', 'time', 'let', 'alon', 'vega'], ['like'], ['burritto', 'blah'], ['food', 'amaz'], ['servic', 'also', 'cute'], ['could', 'care', 'less', 'interior', 'beauti'], ['perform'], ['that', 'rightth', 'red', 'velvet', 'cakeohhh', 'stuff', 'good'], ['never

In [27]:
len(corpusdata)

1000

In [28]:
print(corpusdata[599])

good money


In [19]:
datatsv["Review"]

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object

In [62]:
f##rom enum import unique
##from collections import Counter

##count=Counter(review)

##uniq=set(corpusdata)
freq={}
for i in corpusdata:
    for word in i:
        if word in freq.keys():
            freq[word]+=1
        else:
            freq[word]=1
            
print(len(freq))
        

1638


In [63]:
print(freq)

{'wow': 3, 'love': 33, 'place': 112, 'crust': 2, 'good': 95, 'tasti': 11, 'textur': 3, 'nasti': 3, 'stop': 4, 'late': 2, 'may': 5, 'bank': 1, 'holiday': 1, 'rick': 1, 'steve': 1, 'recommend': 18, 'select': 12, 'menu': 16, 'great': 70, 'price': 21, 'get': 28, 'angri': 1, 'want': 17, 'damn': 4, 'pho': 6, 'honeslti': 1, 'didnt': 13, 'tast': 22, 'fresh': 14, 'potato': 9, 'like': 51, 'rubber': 1, 'could': 16, 'tell': 6, 'made': 17, 'ahead': 1, 'time': 55, 'kept': 5, 'warmer': 1, 'fri': 16, 'touch': 3, 'servic': 84, 'prompt': 1, 'would': 28, 'go': 61, 'back': 61, 'cashier': 2, 'care': 4, 'ever': 28, 'say': 18, 'still': 11, 'end': 4, 'wayyy': 1, 'overpr': 8, 'tri': 17, 'cape': 1, 'cod': 1, 'ravoli': 1, 'chicken': 18, 'cranberrymmmm': 1, 'disgust': 4, 'pretti': 19, 'sure': 8, 'human': 2, 'hair': 2, 'shock': 1, 'sign': 2, 'indic': 1, 'cash': 1, 'highli': 4, 'waitress': 9, 'littl': 10, 'slow': 11, 'worth': 10, 'let': 4, 'alon': 1, 'vega': 21, 'burritto': 1, 'blah': 1, 'food': 125, 'amaz': 23, 'a

#### Bow

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
cvec=CountVectorizer(max_features=1200)
x=cvec.fit_transform(corpusdata).toarray()
y=datatsv.iloc[:,1].values



In [68]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)


In [69]:
len(x_test)

200

In [70]:
len(x_train)

800

In [73]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [74]:
y_train

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,

## Train model

#### logistic regression

In [75]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

#### evaluation

In [76]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x_test)
print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  0.75


In [77]:
from sklearn.metrics import confusion_matrix
 
cm = confusion_matrix(y_test, y_pred)
 
cm

array([[79, 18],
       [32, 71]], dtype=int64)

### Random forest (best one so far)

In [103]:
from sklearn.ensemble import RandomForestClassifier
mod=RandomForestClassifier(n_estimators=500,criterion="entropy")
mod.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=500)

In [104]:
y_pred = mod.predict(x_test)
print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  0.77


In [105]:
cm = confusion_matrix(y_test, y_pred)
 
cm

array([[81, 16],
       [30, 73]], dtype=int64)

#### Naive byes

In [86]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)


GaussianNB()

In [87]:
y_pred=classifier.predict(x_test)

In [88]:
print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  0.73


In [89]:
cm = confusion_matrix(y_test, y_pred)
 
cm

array([[56, 41],
       [13, 90]], dtype=int64)